import { getSession } from "next-auth/client";
import Head from "next/head";
import { useContext } from "react";
import { Header, Login, Sidebar, Feed, Widgets } from "../components";
import { MainContext } from "../contexts/MainContext";
import { db } from "../firebase";

export default function Home({ session, posts }) {
  if (!session) return <Login />;
  
  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex">
        <Sidebar />
        <Feed posts={posts} />
        <Widgets />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  const posts = await db.collection("posts").orderBy("timestamp", "desc").get();
  const docs = posts.docs.map((post) => ({
    id: post.id,
    ...post.data(),
    timestamp: null,
  }));
  return {
    props: {
      session,
      posts: docs,
    },
  };
}
